/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TodoInput {
    }
    interface TodoItem {
        "checked": boolean;
        "index": number;
        "text": string;
    }
    interface TodoList {
    }
}
declare global {
    interface HTMLTodoInputElement extends Components.TodoInput, HTMLStencilElement {
    }
    var HTMLTodoInputElement: {
        prototype: HTMLTodoInputElement;
        new (): HTMLTodoInputElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "todo-input": HTMLTodoInputElement;
        "todo-item": HTMLTodoItemElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface TodoInput {
        "onOnTodoInputSubmit"?: (event: CustomEvent<any>) => void;
    }
    interface TodoItem {
        "checked"?: boolean;
        "index"?: number;
        "onOnTodoItemChecked"?: (event: CustomEvent<any>) => void;
        "onOnTodoItemRemove"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface TodoList {
    }
    interface IntrinsicElements {
        "todo-input": TodoInput;
        "todo-item": TodoItem;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "todo-input": LocalJSX.TodoInput & JSXBase.HTMLAttributes<HTMLTodoInputElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
